chb-mit:
  database: ../../Data/ChbmitRaw/
  metadata: ../metadata/chb-mit/
  windows: ../../processeddata/ProcessedDataChbMit_fs{}/
  channels: ../etc/channels_chb-mit.txt
  seizure_records: ../etc/RECORDS-WITH-SEIZURES_chb-mit
  metadata_file_json: ../etc/metadata_chb-mit.json
  metadata_file_csv: ../etc/metadata_chb-mit.csv
  grid_search: ../../mldata/MLDataChbmit_fs{}/GridSearch/
  correlation: ../../mldata/MLDataChbmit_fs{}/Correlation/corr_coefs.pickle
  features_map_file: ../etc/features_map_chbmit_fs{}.json
  fs: 256
  num_channels: 23
  length: 512
  noictal_sample_step: 512
  ictal_sample_step: 256
  gain: 2.559375
  units: 0.000001  # Microvots
  part_for_grid: 0.10

siena:
  database: ../../Data/SienaRaw/
  metadata: ../metadata/siena/
  windows: ../../processeddata/ProcessedDataSiena_fs{}/
  channels: ../etc/channels_siena.txt
  metadata_file_json: ../etc/metadata_siena.json
  metadata_file_csv: ../etc/metadata_siena.csv
  features_map_file: ../etc/features_map_siena_fs{}.json
  correlation: ../../mldata/MLDataSiena_fs{}/Correlation/corr_coefs.pickle
  fs: 512
  num_channels: 18
  length: 1024
  noictal_sample_step: 1024
  ictal_sample_step: 512
  gain: 1
  units: 0.000001  # Microvots
